version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies.....
      - npm install
  build:
    commands:
      - echo Building app....
      - npm run build
  post_build:
    commands:
      - echo Deploying to S3....
      - aws s3 sync dist/ s3://static-site-cicd/ --delete

artifacts:
  files:
    - '**/*'
  base-directory: dist
