version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies.....
      - npm install
  build:
    commands:
      - echo Building app....
      - npm run build
      - echo Listing files in the root directory
      - ls -al
      - echo Listing files in the build directory
      - ls -al build/
  post_build:
    commands:
      - echo Verifying build/ directory...
      - ls -al build/   # Check if build/ exists
      - echo Deploying to S3....
      - aws s3 sync dist/ s3://static-site-cicd/ --delete

artifacts:
  files:
    - '**/*'
  base-directory: build
